### PR TITLE
Added AI Trivia Frame

### PR DESCRIPTION
**Pull request by Tech-axis**
Frame link - [ai-trivia-frame](https://ai-trivia-frame.netlify.app/)

### CODE REVIEW

**Comment by fabriguespe** [comment]
Congratulations on your PR being merged! This means that you are now eligible for the Bounty. If you did not submit through ETH Global, kindly share your Converse address with us so that we can send you your USDC.

Please note that we are still in the process of finalizing the reviews, so please bear with us. Open Frames was a huge success with over 100 frames integrated, and we wanted to thank you for your valuable contributions.

**Comment by Tech-axis** [comment]
Converse Address & Coinbase Eth
0x2A116d4722B69bc5D1c3108aD974eEE37aA690Ae

**Comment by Tech-axis** [comment]
hi @fabriguespe, sorry if this comes out as being desperate, I have not received the bounty yet, can you please let me when I would receive it?

by the way here's my address - 0x2A116d4722B69bc5D1c3108aD974eEE37aA690Ae

**Comment by fabriguespe** [comment]
Check your dms!

**Pull request merged**
