### PR TITLE
add example: fundcaster

### PR DESCRIPTION
**Pull request by bhargavkakadiya**
Fundcaster is fundraising Frame app that is compliant with OF specs.

### CODE REVIEW

**Comment by bhargavkakadiya** [comment]
hi @fabriguespe I see this PR wasn't merged, is there anything I can do?

**Comment by fabriguespe** [comment]
Hey! Frame is not rendering properly in apps and also buttons dont work :s

**Comment by bhargavkakadiya** [comment]
I observed same with converse web app and dev-inbox app,
I added this in my existing frames 
image
Is there something more I can do to make it compatible?

**Comment by bhargavkakadiya** [comment]
Also adding more context: the Create button for the frame submitted here is making a tx call
image

**Pull request closed without merging**
