### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by HrithikSampson**

### CODE REVIEW

**Comment by fabriguespe** [comment]
Hey @HrithikSampson Whats the deployed URL?

**Comment by HrithikSampson** [comment]
https://tvlopenframe-3dface52cafd.herokuapp.com/

**Comment by fabriguespe** [comment]
Congratulations on your PR being merged! This means that you are now eligible for the Bounty. If you did not submit through ETH Global, kindly share your Converse address with us so that we can send you your USDC.

Please note that we are still in the process of finalizing the reviews, so please bear with us. Open Frames was a huge success with over 100 frames integrated, and we wanted to thank you for your valuable contributions.

**Comment by HrithikSampson** [comment]
Hi @fabriguespe , I have submitted through Eth global

**Comment by fabriguespe** [comment]
Yo! @HrithikSampson , still URLs not working :s

https://tvlopenframe-3dface52cafd.herokuapp.com/
https://tvl-history.vercel.app/

Can you test them?

**Comment by HrithikSampson** [comment]
Hi @fabriguespe 

The Vercel Deployment URL wasnt working sincee there is an Issue with node canvas library isnt being supported in vercel hence I had removed it from vercel and deplyed it in Heroku

I tested this link it worked for me

https://tvlopenframe-3dface52cafd.herokuapp.com/

**Pull request merged**
