### PR TITLE
Added meme generator farcaster

### PR DESCRIPTION
**Pull request by ajaybutti**
Can generate memes within farcaster

### CODE REVIEW

**Review by fabriguespe — APPROVED** [review]

**Comment by fabriguespe** [comment]
Hey @ajaybutti. Do you have a live URL to try?

**Comment by ajaybutti** [comment]
yeah its right in the repository , successfully merged what should be my next step

**Comment by fabriguespe** [comment]
Please share your address for converse!

**Comment by ajaybutti** [comment]
0xd0fe99efccDA82b0C77a7fc60C538b98A1Ad5268

**Comment by ajaybutti** [comment]
0xd0fe99efccDA82b0C77a7fc60C538b98A1Ad5268

**Pull request merged**
