### PR TITLE
 BOUNTY: Added Frames Trending Tokens to the open-source list

### PR DESCRIPTION
**Pull request by vividwood**
Frames Trending Tokens: https://github.com/vividwood/frames-trending-tokens 
Submission for Frameworks Hackathon

### CODE REVIEW

**Comment by vividwood** [comment]
> Hey @vividwood ! Can you share the deloyed url?

Hey! Here https://frames-trending-tokens.onrender.com/

**Comment by fabriguespe** [comment]
@vividwood thks! it's failing to render.

**Comment by vividwood** [comment]
> @vividwood thks! it's failing to render.

Hmm, it rendered fine for me in Converse. Can you try https://frames-trending-tokens.onrender.com/frames ?

**Comment by fabriguespe** [comment]
Got it. renders the first image but then fails on the buttons.

**Comment by vividwood** [comment]
> @vividwood thks! it's failing to render.

image
Both seem to work

**Comment by vividwood** [comment]
> Got it. renders the first image but then fails on the buttons.

Yea, I thought that's because it can't render base64 images. I can fix that I think, I'll let you know if it works

**Comment by fabriguespe** [comment]
You can try here too [DevInbox](https://dev-inbox.vercel.app/)

**Comment by vividwood** [comment]
> You can try here too [DevInbox](https://dev-inbox.vercel.app/)

Is there a way to test it locally? I can make separate pages load, but I can't make buttons work and I have no idea why

**Comment by fabriguespe** [comment]
You are probably doing a Farcaster validator? You can test locally by running the dev inbox locally too! https://github.com/xmtp/dev-inbox

**Comment by vividwood** [comment]
> You are probably doing a Farcaster validator? You can test locally by running the dev inbox locally too! https://github.com/xmtp/dev-inbox
> 
> You can ping me via Discord!

Hi, it works know. Could you reopen PR please :pray:

**Pull request closed without merging**
